### ISSUE TITLE
Подготовить ТЗ

### ISSUE THREAD

**Issue by wldmr-key** [Kaserss/Course-database#1]
Пока что ТЗ является таковым по форме, но не по существу. Из ТЗ непонятно, кто готовит домашнюю еду, и какие конкретно функции выполняет сервис

Необходимы, как минимум, характеристика объекта автоматизации и функциональные характеристики (перечень функций) системы...

**Comment by wldmr-key** [comment]
Если меняешь документы, то меняй их синхронно. Откуда мне знать, где более правильный файл - здесь или в ЭОС. И пока что змаечания по ТЗ не устранены...

**Comment by Kaserss** [comment]
Залил синхронно и в ЭОС и на Гитхаб. Вроде, исправил замечания
